### PR TITLE
[configure] Fix OpenMP CXXFLAGS

### LINKED ISSUE #272: Build broken by PR #266
@fredRos, your PR #266 broke the build, somehow:

```
cd /path/to/build
/path/to/bat/configure --prefix=/path/to/inst --with-cuba=download --enable-roostats --enable-parallel
make -j`nprocs` install
```

now fails with

```
../../../../src/.libs/libBAT.so: undefined reference to `omp_get_max_threads'
../../../../src/.libs/libBAT.so: undefined reference to `omp_get_thread_num'
```

Using the updated (now with ROOT v6.12.06) centos7-root6 [BAT test container image](https://hub.docker.com/r/batk/bat-testenv/tags/).

Doesn't happen on Travis, for some reason.

### PR DESCRIPTION
**Pull request by fredRos**
fixes #272 

Having cuba configured during configure is a bit annoying but I found a solution that works

### CODE REVIEW

**Comment by fredRos** [comment]
I have tested this in our docker container with root6 and it works. No idea why `make distcheck` didn't catch that problem. Now we properly tell autoconf that BAT uses C++
