### ISSUE TITLE
Build broken by PR #266

### ISSUE THREAD

**Issue by oschulz** [bat/bat#272]
@fredRos, your PR #266 broke the build, somehow:

```
cd /path/to/build
/path/to/bat/configure --prefix=/path/to/inst --with-cuba=download --enable-roostats --enable-parallel
make -j`nprocs` install
```

now fails with

```
../../../../src/.libs/libBAT.so: undefined reference to `omp_get_max_threads'
../../../../src/.libs/libBAT.so: undefined reference to `omp_get_thread_num'
```

Using the updated (now with ROOT v6.12.06) centos7-root6 [BAT test container image](https://hub.docker.com/r/batk/bat-testenv/tags/).

Doesn't happen on Travis, for some reason.

**Comment by oschulz** [comment]
See also #273.

**Comment by fredRos** [comment]
Interesting. I was bulding on Ubuntu 16.04 with g++ 5.4 and ROOT 5.34 and 6.06 and on Debian 8 with g++ g.3 and ROOT v6.12.06  and had no such no such problem. 

I will have a lock with the docker image
